### ISSUE TITLE
running or queue icon

### ISSUE THREAD

**Issue by tankf33der** [TrustInSoft-CI/TrustInSoft-CI#5] opened 2020-06-05 16:54 UTC
if I choose to run **not lastest** job again inside any project then I **don't** see running or queue icon of project in dashboard.

**Comment by guillaumemillot** [comment] 2020-06-08 10:01
Hi Mike, I haven't been able to reproduce the issue: do you mind sharing the exact steps? Thanks!

**Comment by tankf33der** [comment] 2020-06-08 10:30
again:

if I choose to run not lastest job again inside any project ...

![image](https://user-images.githubusercontent.com/45243121/84020729-f689dd80-a98b-11ea-96da-fff479ec2064.png)

...then I don't see running or queue icon of project in dashboard.

![image](https://user-images.githubusercontent.com/45243121/84020752-fee21880-a98b-11ea-993d-55358f32a330.png)

**Comment by tankf33der** [comment] 2020-06-08 11:08
when I would rerun job number _2_ (**latest**) in monocypher1-tis project I would see sand clock icon in dash boards.

**Comment by guillaumemillot** [comment] 2020-06-08 11:23
Ok I see. In the dashboard, you don't see the clock icon when re-running job number 1 because the dashboard always shows the status/result of the latest created job, so job number 2 in that case.

Let me know if we should clarify it in the dashboard or you'd rather see something else.

**Comment by tankf33der** [comment] 2020-06-08 11:34
Dashboard is the only place where I **can** see status of all projects, i want to see what is running and what is finished. When you switch to bigger RAM I rerun 3 projects and have had to click one project to check what the current status inside.

**Comment by guillaumemillot** [comment] 2020-06-08 12:15
I understand your point. I looked at other dashboards such as Travis, and it's the same thing: you need to select the project to see all jobs instead of the last one.

On TIS CI, 2 clicks are needed to see all jobs:
1) Click on a project in the dashboard sends you to the latest created job
2) Then, click on the project name in the navigation path to see all jobs:
![image](https://user-images.githubusercontent.com/10330584/84029595-f214f300-a992-11ea-8d9f-b96719773a82.png)

We can make it in one click if you want:
1) Click on a project in the dashboard can send you to all jobs

Let me know what you think.

Also, do you expect to often re-run jobs?

**Comment by tankf33der** [comment] 2020-06-08 13:07
I never had account in any CI. In general - I dont care.

All I am writing is how I feel it should be or how I would implement it.

**My** Idea behind dashboard is:
- dashboard is place where you see all projects and is anything running inside them right now?

You offer me to clone behavior of Travis (who cares about Travis, come on!) and implement **idea**:
- dashboard is place where you see all projects and is latest task running inside them right now?

I choose mine. 




    Also, do you expect to often re-run jobs?
Wrong question for this issue, correct one should be - do you expect to often re-run non-latest jobs?
Answer: I and any user already have ability to re-run non-latest jobs and you should provide feature to see is it still running or not **from** dashboard.

Feel free to close issue.

**Comment by guillaumemillot** [comment] 2020-06-08 17:13
Thanks for your insight, I now understand the need - see all the running verifications **from** the dashboard - and will keep it in mind for the future.

Right now, I'm focusing on the features already discussed in the other issues and email thread, as they seem more important to you (please correct if wrong).

Closing the issue.

**Closed as completed by guillaumemillot** 2020-06-08 17:13 UTC
